name: SurvivalGames
author: maker56
main: me.maker56.survivalgames.SurvivalGames
version: Beta 1.9.2
softdepend: [WorldEdit,Vault,Multiverse-Core,BarAPI]

commands:
  sg:
    description: SurvivalGames Main Command
    aliases: [survivalgames,sg,hg,hungergames]